### ISSUE TITLE
Cannot submit presenter registration

### ISSUE THREAD

**Issue by deweyhulsey** [swatkins/k20expresspass#1]
**At the Who Are You? screen (https://i.imgur.com/GV2LK5v.png | https://k20center.ou.edu/expresspass/registration)**

Selecting either attendee, presenter, or vendor appends/prepends an addition 'expresspass' to the url. This might be causing some issues.

**After filling out the presenter registration and hitting 'complete registration' (https://i.imgur.com/l8Rk8OC.png | https://k20center.ou.edu/expresspass/expresspass/registration/presenter)**

The complete registration button takes you here https://k20center.ou.edu/expresspass/expresspass/registration/presenter with following error: "Whoops, looks like something went wrong."

**Comment by swatkins** [comment]
@deweyhulsey This commit should fix that - was using relative routes instead of absolute

**Comment by deweyhulsey** [comment]
@swatkins I pulled in the change, but it still seems to be doing the same thing for me. Does a cache need to be cleared perhaps?

**Comment by swatkins** [comment]
Maybe, can you do a `php artisan route:clear`

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by deweyhulsey** [comment]
@swatkins still getting the same thing. :<

**Comment by swatkins** [comment]
OK I’ll take a quick look and see if I can get it finished in the next hour or so

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
